### ISSUE TITLE
test_pack_ext_handler (__main__.TestUmsgpack) for ppc64 (BE)

### ISSUE THREAD

**Issue by michelmno** [vsergeev/u-msgpack-python#30]
two failing tests for ppc64 (BE)   for version 2.3.0

Reported while openSUSE build
https://build.opensuse.org/package/live_build_log/openSUSE:Factory:PowerPC/python-u-msgpack-python/standard/ppc64
```
[   19s] ======================================================================
[   19s] FAIL: test_pack_ext_handler (__main__.TestUmsgpack)
[   19s] ----------------------------------------------------------------------
[   19s] Traceback (most recent call last):
[   19s]   File "test_umsgpack.py", line 389, in test_pack_ext_handler
[   19s]     self.assertEqual(umsgpack.packb(obj, ext_handlers=ext_handlers), data)
[   19s] AssertionError: '\xd7 ?\x80\x00\x00@\x00\x00\x00' != '\xd7 \x00\x00\x80?\x00\x00\x00@'
[   19s]
[   19s] ======================================================================
[   19s] FAIL: test_unpack_ext_handler (__main__.TestUmsgpack)
[   19s] ----------------------------------------------------------------------
[   19s] Traceback (most recent call last):
[   19s]   File "test_umsgpack.py", line 395, in test_unpack_ext_handler
[   19s]     self.assertEqual(umsgpack.unpackb(data, ext_handlers=ext_handlers), obj)
[   19s] AssertionError: (4.600602988224807e-41+8.96831017167883e-44j) != (1+2j)
[   19s]
[   19s] ----------------------------------------------------------------------
```

**Comment by vsergeev** [comment]
Thanks for the report. Fixed in #31.
