### ISSUE TITLE
Test failures on Python 3.9

### ISSUE THREAD

**Issue by stratakis** [vsergeev/u-msgpack-python#44]
Running the tests on Python 3.9 make two test cases fail.

ERROR: test_unpack_composite (test_umsgpack.TestUmsgpack)
Traceback (most recent call last):
  File "/builddir/build/BUILD/u-msgpack-python-2.5.0/test_umsgpack.py", line 439, in test_unpack_composite
    self.assertEqual(umsgpack.unpackb(data), obj)
  File "/builddir/build/BUILD/u-msgpack-python-2.5.0/umsgpack.py", line 1019, in _unpackb3
    return _unpack(io.BytesIO(s), options)
  File "/builddir/build/BUILD/u-msgpack-python-2.5.0/umsgpack.py", line 833, in _unpack
    return _unpack_dispatch_table[code](code, fp, options)
  File "/builddir/build/BUILD/u-msgpack-python-2.5.0/umsgpack.py", line 813, in _unpack_map
    elif not isinstance(k, collections.Hashable):
AttributeError: module 'collections' has no attribute 'Hashable'

ERROR: test_unpack_exceptions (test_umsgpack.TestUmsgpack)
Traceback (most recent call last):
  File "/builddir/build/BUILD/u-msgpack-python-2.5.0/test_umsgpack.py", line 446, in test_unpack_exceptions
    umsgpack.unpackb(data)
  File "/builddir/build/BUILD/u-msgpack-python-2.5.0/umsgpack.py", line 1019, in _unpackb3
    return _unpack(io.BytesIO(s), options)
  File "/builddir/build/BUILD/u-msgpack-python-2.5.0/umsgpack.py", line 833, in _unpack
    return _unpack_dispatch_table[code](code, fp, options)
  File "/builddir/build/BUILD/u-msgpack-python-2.5.0/umsgpack.py", line 813, in _unpack_map
    elif not isinstance(k, collections.Hashable):
AttributeError: module 'collections' has no attribute 'Hashable'

This is due to the classes from collections.abc not being exposed anymore through the collections module: https://docs.python.org/3.9/whatsnew/3.9.html#removed

In that case `Hashable` needs to be imported from `collections.abc`

**Comment by hroncok** [comment]
Fixed in 5ece62affdd47ac28a5737119653ff861d8008ee

**Comment by stratakis** [comment]
Ah we need to update our package then. Closing this and sorry for the noise.
